modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
[[mods]] 
modId="personforgeorigins" 
version="1.0"
displayName="Forge Origins"
logoFile="examplemod.png"
credits="Thanks to Apace100 for the fabric version of this mod"
authors="ThatOnePerson for making the mod. Apace100 for the idea."
description='''
Filler

Uh

Um
'''